DATASET:
  TRAIN_PATH: "/kaggle/input/mesh-dataset/train"
  TEST_PATH: "/kaggle/input/mesh-dataset/test"
  IMAGE_FORMAT: ".jpg"

SAM:
  CHECKPOINT: "/kaggle/working/sam_vit_b_01ec64.pth"
  RANK: 512

TRAIN:
  BATCH_SIZE: 1
  NUM_EPOCHS: 50
  LEARNING_RATE: 0.0001
